---
- name: create deployment directory
  file:
    path: '{{ DEPLOYMENT_ROOT }}'
    state: directory
    mode: 0755

- name: copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: '{{ DEPLOYMENT_ROOT }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0644

- name: generate .env
  blockinfile:
    path: '{{ DEPLOYMENT_ROOT }}/.env'
    create: yes
    owner: root
    group: root
    mode: 0644
    block: |
      DEPLOYMENT_ROOT={{ DEPLOYMENT_ROOT }}

      POSTGRES_IMAGE={{ POSTGRES_IMAGE }}
      CASSANDRA_IMAGE={{ CASSANDRA_IMAGE }}
      ZOOKEEPER_IMAGE={{ ZOOKEEPER_IMAGE }}
      KAFKA_IMAGE={{ KAFKA_IMAGE }}
      SCHEMA_REGISTRY_IMAGE={{ SCHEMA_REGISTRY_IMAGE }}

      POSTGRES_PASSWORD={{ POSTGRES_PASSWORD }}
      HOST_IP={{ HOST_IP }}

- name: start docker
  command: /usr/local/bin/docker-compose up -d
  args:
    chdir: '{{ DEPLOYMENT_ROOT }}'
