version: "3"
services:
  mysql:
    image: ${MYSQL_IMAGE}
    ports:
      - 33306:3306
    volumes:
      - "mysql:/var/lib/mysql:z"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    restart: always
  cassandra:
    image: ${CASSANDRA_IMAGE}
    ports:
      - 39042:9042
    volumes:
      - "cassandra:/var/lib/cassandra:z"
    restart: always
  zookeeper:
    image: ${ZOOKEEPER_IMAGE}
    network_mode: "host"
    volumes:
      - "zookeeper:/var/lib/zookeeper/data:z"
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
    restart: always
  kafka:
    image: ${KAFKA_IMAGE}
    depends_on:
      - zookeeper
    network_mode: "host"
    volumes:
      - "kafka:/var/lib/kafka/data:z"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=${HOST_IP}:32181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${HOST_IP}:39092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    restart: always
  schema-registry:
    image: ${SCHEMA_REGISTRY_IMAGE}
    depends_on:
      - zookeeper
    network_mode: "host"
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=${HOST_IP}:32181
      - SCHEMA_REGISTRY_HOST_NAME=${HOST_IP}
      - SCHEMA_REGISTRY_LISTENERS=http://${HOST_IP}:38081
    restart: always
volumes:
  mysql:
  cassandra:
  zookeeper:
  kafka:
